name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '11 4 * * *'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
    runs-on: ubuntu-latest
    env:
      GIT_SSL_NO_VERIFY: "true"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-platforms = i686-linux aarch64-linux arm-linux
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: weiss
    - name: Build nix packages
      run: |
        nix flake update
        nix run .#ci -- ${{ matrix.system }}
